[build]
builder = "dockerfile"

[deploy]
startCommand = "sh -c 'uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}'"
restartPolicyType = "ON_FAILURE"

[env]
PYTHONPATH = "/app"
# SMTP Configuration (Set these in Railway Environment Variables)
# SMTP_SERVER = "smtp.gmail.com"
# SMTP_PORT = "587"
# SMTP_USERNAME = "your-email@gmail.com"
# SMTP_PASSWORD = "your-app-password"
# FROM_EMAIL = "your-email@gmail.com"
# FROM_NAME = "File Split Tool"